name: schp
channels:
  - nvidia
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - numpy=1.19.2
  - pandas=1.1.4
  - scipy=1.7.3
  - pytorch=1.7.0
  - torchvision=0.8.0
  - cudatoolkit=10.1
  - cudnn=7.6
  - pip
  - pip:
      - flask>=2.0.0
      - werkzeug==2.2.3
      - opencv-python-headless==4.5.5.64
      - ultralytics==8.0.20
      - requests>=2.25.0
      - urllib3>=1.26.0
